---
title: "Homework"
sidebar: false
---

Note: problem sets will be updated with new questions following each class. Completed homework should be submitted to Canvas unless otherwise noted.

-   [Problem Set 1](weeks/hw/310_hw1.pdf): covers material from 2/09-2/13
    -   Due: 2/17 at 11:59pm
-   [Problem Set 2](weeks/hw/310_hw2.pdf): covers material from 2/16-2/20
    -   Due: 2/24 at 11:59pm
    -   Associated `.Rmd` file: {{< downloadthis weeks/hw/310_hw2_R.Rmd dname="hw2_R" label="hw2_R" id=mtcars-btn >}}
-   [Problem Set 3](weeks/hw/310_hw3.pdf): covers material from 2/23-2/27
    -   Due 3/03 at 11:59pm
-   [Problem Set 4](weeks/hw/310_hw4.pdf): covers material from 3/02-3/06
    -   Due 3/10 at 11:59pm
-   Problem Set 5:
    -   **Note: there was a typo on question 1.** In the theorem, the term on the right should be $(1+v)^{-n}$, not $(1+v)^{n}$. (Fixed as of 9:00pm 3/17)
    -   [Option 1](weeks/hw/310_hw5.pdf): covers material from 3/09-3/16
        -   Due 3/20 at 11:59pm
    -   [Option 2](weeks/hw/310_hw5_opt2.pdf): covers material from 3/09-3/18
        -   Due: 3/30 at 11:59pm
-   Problem Set 6 (stick with the option you did for Problem Set 5)
    -   [Option 1](weeks/hw/310_hw6.pdf): covers material from 3/18-4/03
    -   [Option 2](weeks/hw/310_hw6_opt2.pdf): covers material from 3/20-4/03
    -   Due 4/07 at 11:59pm
-   [Problem Set 7](weeks/hw/310_hw7.pdf): covers material from 4/06-4/10
    -   Due 4/14 at 11:59pm
-   [Problem Set 8](weeks/hw/310_hw8.pdf): covers material from 4/13-4/15
    -   Due **Monday** 4/20 at 11:59pm (note earlier due date due to shorter problem set + time to grade before Midterm 2)
-   [Problem Set 9](weeks/hw/310_hw9.pdf): covers material from 4/27-5/01
    -   Due 5/05 at 11:59pm
