---
title: "Probability"
sidebar: false
---

Welcome to the website for Middlebury College's Spring 2026 MATH/STAT 310. On this website you will find the course syllabus, schedule, and assignments. The website is frequently updated during the semester, so please make a habit of refreshing the page. The icons at the top right will link to the online version of the textbook and Canvas.

## Major Announcements

-   Statistics talk: *Feel the noise: A statistical journey through the resolution of a low frequency noise issue* by Richard Single (UVM)
    -   Monday 3/9 at 3:30pm in WNS 104
    -   More information [here](https://www.middlebury.edu/events/event/feel-noise-statistical-journey-through-resolution-low-frequency-noise-issue)
-   Modified office hours
    -   Monday 3/9 from 2:00-3:30pm (then go to the talk!)
    -   Wednesday 3/11 from 3:30-4:30pm (extra!)
    -   Additional TA hours: Thursday 3/12 from 7:00-9:00pm in WNS 011

## Course Details

Instructor: Becky Tang

-   Office: WNS 214
-   Email: btang\@middlebury.edu

Meeting times: MWF 1:10-2:00pm in WNS 011

Office hours: M 2:30-4:00pm, T 3:30-4:30pm, R 11:00am-12:00pm

Shingo's TA hours: T 7:00-9:00pm (WNS 011)

[Syllabus](syllabus/stat310_syllabus.pdf) (most recent update: 02/02/26)
