---
title: "Assessments"
sidebar: false
toc: true
---

## **Midterm 1**

### What and when

-   Friday, March 13 from 1:15-3:15pm in WNS 011 (our usual classroom)
-   Content through Friday, March 6 is fair game
-   You are allowed one, single-sided note sheet (8.5x11 inches)
    -   Your note sheet cannot include any worked out examples/derivations
    -   I **highly recommend** you write out the PMFs (including supports) and means for our named distributions that we've learned through March 6. Some of them will most likely appear on the midterm and I will not provide their PMFs for you.
-   Problem set 5 will be due the Friday before spring break

### Study tips

-   Review notes and homework, do the extra practice problems associated with each class
-   Extra practice problems are available [here](midterm1_practice_probs.pdf)!
-   Come to office hours!!
-   My personal working strategy:
    1.  First review your notes
    2.  Make a first draft of your note sheet, then do some practice problems using only your note sheet to see if what you wrote on it is actually useful for you
    3.  Make a new note sheet
    4.  Repeat as necessary
